-- telescope keybindings
vim.keymap.set('n', '<leader>ff', '<cmd>Telescope find_files<CR>')
vim.keymap.set("n", "<leader>fg", "<cmd>Telescope live_grep<cr>")
vim.keymap.set("n", "<leader>fb", "<cmd>Telescope buffers<cr>")
vim.keymap.set("n", "<leader>fm", "<cmd>Telescope marks<cr>")
vim.keymap.set("n", "<leader>fr", "<cmd>Telescope lsp_references<cr>")
vim.keymap.set("n", "<leader>fs", "<cmd>Telescope lsp_document_symbols<cr>")
vim.keymap.set("n", "<leader>fc", "<cmd>Telescope lsp_incoming_calls<cr>")
vim.keymap.set("n", "<leader>fo", "<cmd>Telescope lsp_outgoing_calls<cr>")
vim.keymap.set("n", "<leader>fi", "<cmd>Telescope lsp_implementations<cr>")
vim.keymap.set("n", "<leader>fx", "<cmd>Telescope diagnostics bufnr=0<cr>")
